'use client';
import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { useParams, useSearchParams } from 'next/navigation';
import { io, Socket } from 'socket.io-client';
import { parseVideoUrl } from '@/lib/video/parseVideoUrl';
import { PlaybackState } from '@/lib/video/types';
import { YouTubeAdapter } from '@/lib/video/YouTubeAdapter';
import { VkVideoAdapter } from '@/lib/video/VkVideoAdapter';
import { PlayerSyncController } from '@/lib/video/PlayerSyncController';
const SERVER_URL = process.env.NEXT_PUBLIC_SOCKET_URL ?? 'https://hardumo.onrender.com';
export default function RoomPage(){ const {roomId}=useParams<{roomId:string}>(); const search=useSearchParams(); const [name,setName]=useState(''); const [joined,setJoined]=useState(false); const [videoInput,setVideoInput]=useState(search.get('video')??''); const [users,setUsers]=useState<any[]>([]); const [messages,setMessages]=useState<any[]>([]); const [messageText,setMessageText]=useState('');
const [isHost,setIsHost]=useState(false); const [showGuestOverlay,setShowGuestOverlay]=useState(false); const [overlayMessage,setOverlayMessage]=useState('Синхронизироваться и начать просмотр'); const [syncStatus,setSyncStatus]=useState('Ожидание синхронизации');
const socketRef=useRef<Socket|null>(null); const containerRef=useRef<HTMLDivElement>(null); const adapterRef=useRef<any>(null); const syncRef=useRef<PlayerSyncController|null>(null); const lastHostSeekEmitAtRef=useRef(0);
const playerReadyRef=useRef(false); const userActivatedSyncRef=useRef(false); const pendingRemoteStateRef=useRef<PlaybackState|null>(null); const applyingRemoteStateRef=useRef(false); const lastServerStateRef=useRef<PlaybackState|null>(null); const isHostRef=useRef(false); const lastSeqRef=useRef(0);
const video=useMemo(()=>parseVideoUrl(videoInput),[videoInput]);
useEffect(()=>{ if(!joined||!video||!containerRef.current) return; playerReadyRef.current=false; pendingRemoteStateRef.current=null; lastSeqRef.current=0; applyingRemoteStateRef.current=false; if(!isHostRef.current) setShowGuestOverlay(true); console.log('[VIDEO CHANGE RESET]',{provider:video.provider,videoId:video.videoId}); adapterRef.current?.destroy?.(); const adapter=video.provider==='youtube'?new YouTubeAdapter({isHost:isHostRef.current}):new VkVideoAdapter(); adapterRef.current=adapter; syncRef.current=new PlayerSyncController({roomId,adapter,isHostRef,playerReadyRef,userActivatedSyncRef,pendingRemoteStateRef,applyingRemoteStateRef,lastServerStateRef,lastSeqRef,setShowGuestOverlay,setSyncStatus});
adapter.onReady(()=>{ playerReadyRef.current=true; console.log('[PLAYER] ready'); if(isHostRef.current) userActivatedSyncRef.current=true; syncRef.current?.applyPendingRemoteState();});
adapter.onStateChange(async(state:any)=>{ if(applyingRemoteStateRef.current){ console.log('[PLAYER] ignoring state change caused by remote sync'); return; } if(!isHostRef.current){ console.log('[PLAYER] guest state change ignored'); return; } const t=await adapter.getCurrentTime(); if(state==='playing') socketRef.current?.emit('video:control',{roomId,type:'play',position:t}); if(state==='paused'||state==='ended') socketRef.current?.emit('video:control',{roomId,type:'pause',position:t}); });
adapter.onAutoplayBlocked?.(()=>{ console.warn('[PLAYER] autoplay blocked'); if(!isHostRef.current){ userActivatedSyncRef.current=false; setShowGuestOverlay(true); setOverlayMessage('Браузер заблокировал автозапуск. Нажмите, чтобы продолжить синхронный просмотр'); }});
adapter.load(containerRef.current,video); return ()=>adapter.destroy?.(); },[joined,video?.provider,video?.videoId,video?.embedUrl]);

useEffect(()=>{ if(!joined) return; const socket=io(SERVER_URL); socketRef.current=socket; socket.emit('room:join',{roomId,name,provider:video?.provider,videoId:video?.videoId,embedUrl:video?.embedUrl});
socket.on('room:state',(state)=>{ console.log('[ROOM] state received',state); setUsers(state.users); setMessages(state.messages??[]); setIsHost(state.isHost); isHostRef.current=state.isHost; if(state.isHost){ userActivatedSyncRef.current=true; setShowGuestOverlay(false);} else { userActivatedSyncRef.current=false; setShowGuestOverlay(true);} if(state.playback) syncRef.current?.queueOrApplyRemoteState(state.playback); });
socket.on('presence:update',({users,hostId})=>{ setUsers(users); const host=hostId===socket.id; setIsHost(host); isHostRef.current=host; }); socket.on('chat:new',(m)=>setMessages((p)=>[...p,m]));
socket.on('room:playback-state',(playback)=>{ console.log('[SYNC] playback state received',playback); syncRef.current?.queueOrApplyRemoteState(playback); }); socket.on('room:sync-pulse',(playback)=>{ lastServerStateRef.current=playback; }); socket.on('control:denied',(payload)=>{ console.warn('[CONTROL DENIED]',payload); setSyncStatus('Только создатель комнаты может управлять видео'); });
return ()=>{ socket.off('room:state'); socket.off('presence:update'); socket.off('chat:new'); socket.off('room:playback-state'); socket.off('room:sync-pulse'); socket.off('control:denied'); socket.disconnect(); }; },[joined,roomId,name,video?.provider,video?.videoId,video?.embedUrl]);

useEffect(()=>{ const interval=setInterval(async()=>{ if(isHostRef.current||!playerReadyRef.current||!userActivatedSyncRef.current||!adapterRef.current) return; const state=lastServerStateRef.current; if(!state||!state.isPlaying) return; const target=syncRef.current?.getResolvedTargetTime(state)??state.position; const current=await adapterRef.current.getCurrentTime(); const diff=target-current; if(Math.abs(diff)>1.25){ console.log('[DRIFT] hard correction',{diff,target,current}); applyingRemoteStateRef.current=true; await adapterRef.current.seekTo(target); setTimeout(()=>applyingRemoteStateRef.current=false,700); return;} if(Math.abs(diff)>0.35){ console.log('[DRIFT] soft correction',{diff,target,current}); try{ const rates=adapterRef.current.getAvailablePlaybackRates?.()||[1]; if(diff>0&&rates.includes(1.25)){ adapterRef.current.setPlaybackRate(1.25); setTimeout(()=>adapterRef.current?.setPlaybackRate(1),1500);} if(diff<0&&rates.includes(0.75)){ adapterRef.current.setPlaybackRate(0.75); setTimeout(()=>adapterRef.current?.setPlaybackRate(1),1500);} } catch(err){ console.warn('[DRIFT] playbackRate correction failed',err); }} },1500); return ()=>clearInterval(interval); },[]);
useEffect(()=>{ const interval=setInterval(async()=>{ if(!isHostRef.current||!playerReadyRef.current||!adapterRef.current||applyingRemoteStateRef.current) return; const socket=socketRef.current; const serverState=lastServerStateRef.current; if(!socket||!serverState?.isPlaying) return; const current=await adapterRef.current.getCurrentTime(); const expected=syncRef.current?.getResolvedTargetTime(serverState)??serverState.position; const diff=Math.abs(expected-current); console.log('[HOST POLL]',{expected,current,diff}); if(diff<=1.25) return; const now=Date.now(); if(now-lastHostSeekEmitAtRef.current<1000) return; lastHostSeekEmitAtRef.current=now; console.log('[SEEK DETECTED]',{roomId,position:current,expected,diff}); socket.emit('video:control',{roomId,type:'seek',position:current}); },700); return ()=>clearInterval(interval); },[roomId]);

if(!joined) return <main className='min-h-screen flex items-center justify-center'><div className='panel p-6'><input value={name} onChange={(e)=>setName(e.target.value)} placeholder='Имя' className='px-3 py-2 bg-black/30 rounded' /><button onClick={()=>setJoined(true)} className='ml-2 bg-accent px-3 py-2 rounded'>Войти</button></div></main>;
return <main className='min-h-screen p-4 space-y-3'><div className='panel p-3 flex gap-2'><input value={videoInput} disabled={!isHost} onChange={(e)=>setVideoInput(e.target.value)} className='flex-1 rounded bg-black/30 px-3 py-1' placeholder='Вставьте ссылку YouTube или VK Видео'/>{isHost&&video?<button className='rounded bg-accent px-3 py-1' onClick={()=>socketRef.current?.emit('room:update-video',{provider:video.provider,videoId:video.videoId,embedUrl:video.embedUrl})}>Обновить комнату</button>:null}<span className='text-xs'>{video?.provider==='vk'?'VK Видео':'YouTube'}</span>{video?.provider==='vk'?<span className='text-xs text-yellow-300'>VK sync: experimental</span>:null}<span className='text-xs'>{syncStatus}</span></div>
<div className='aspect-video bg-black rounded overflow-hidden relative'><div ref={containerRef} className='w-full h-full'/>{showGuestOverlay&&!isHost?<div className='absolute inset-0 bg-black/70 flex flex-col items-center justify-center gap-2'><h3>{overlayMessage}</h3><p className='text-sm text-white/80'>Нажмите, чтобы начать синхронный просмотр</p><button className='rounded bg-accent px-4 py-2' onClick={()=>{ userActivatedSyncRef.current=true; setShowGuestOverlay(false); socketRef.current?.emit('room:request-playback-state',{roomId}); syncRef.current?.applyPendingRemoteState(); }}>Начать просмотр</button></div>:null}</div>
<aside className='panel p-3'><div>Участники: {users.length}</div><form onSubmit={(e:FormEvent)=>{e.preventDefault(); socketRef.current?.emit('chat:send',{text:messageText}); setMessageText('');}} className='mt-2 flex gap-2'><input value={messageText} onChange={(e)=>setMessageText(e.target.value)} className='flex-1 rounded bg-black/30 px-2'/><button className='rounded bg-accent px-3 py-1'>Send</button></form>{messages.map((m:any)=><div key={m.id} className='text-sm'>{m.user}: {m.text}</div>)}</aside></main>; }
